-- Create vehicles table
CREATE TABLE IF NOT EXISTS public.vehicles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  type TEXT NOT NULL,
  time TEXT NOT NULL,
  price REAL NOT NULL,
  original_price REAL,
  image_url TEXT NOT NULL,
  is_ai_recommended BOOLEAN DEFAULT FALSE,
  stats JSONB
);

-- Create routes table
CREATE TABLE IF NOT EXISTS public.routes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type TEXT NOT NULL,
  duration_minutes INTEGER NOT NULL,
  arrival_time TEXT NOT NULL,
  price REAL NOT NULL,
  is_ai_recommended BOOLEAN DEFAULT FALSE,
  segments JSONB
);

-- Insert dummy data for vehicles
INSERT INTO public.vehicles (title, type, time, price, original_price, image_url, is_ai_recommended, stats)
VALUES 
(
  'AI 舒适型', 'comfort', '3 分钟', 45.20, 52.00,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuBJyGygbQad_CZYS89smbh_rTFHfPLz6tpw2pjuKAV0cw2ySOjkYqDUvZQomUYhvaULxmHjQpJfNYaW5KUhcFpaqJR4gIEorwk1vY--3B0F8KAniwU6YylKwzOvNDAj6i36FrnwZi1ZtLhIc1zKSnzVylYcAauaRsrU_iKrKnDqlgkl-NKd1yiuDRqw4Xjcp5UtFWii24NWOu8J-jRBLKh6_s2hVq4FJi-2F6AblEHd_zGC0pM0Y1n3fC8H2JlsXf2lswVB0IO1DN3K',
  TRUE,
  '[{"label": "距离", "value": "1.2 km"}, {"label": "接单速度", "value": "极快"}, {"label": "车辆干净度", "value": "完美"}, {"label": "预估价格", "value": "高确信"}]'::jsonb
),
(
  '优享型', 'premium', '5 分钟', 38.50, NULL,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDQDh4ewSi-8OsuHPPF7KA-YH4aFtLWLNhK8nqTKC9iVpzQbzKAFGLPPSLu2xmRZb78YvaxtveznnhQV3MAHZ5fgl-LpLVw8MEl8L5w9w3N2T77R-_97wDHp1vYME9i6samitpBtkjXCIKi4POVXgjlSz7uTsssxvH_g5FV-TGq7v2DAZe2WkWBBSqTUh4dWlcP-KRY0T5Ni2EYf5tkLZ9zgKShUf4Ro0t9zhrJmv5FNWPHk8fcz_9oUqjnHy09rAmlm178fob_vZng',
  FALSE,
  '[{"label": "距离", "value": "2.5 km"}, {"label": "接单速度", "value": "较快"}, {"label": "车辆干净度", "value": "优良"}]'::jsonb
),
(
  '经济型', 'economy', '8 分钟', 24.00, NULL,
  'https://lh3.googleusercontent.com/aida-public/AB6AXuDnaKC8MlEORK5U8Arwd_avDwhxk95vXLWjJ63S43R2yMBPTb8JD2hUqLw4Or7epDVLtSb5nSZifZqNJ_lkAq61aHbYhc64k6IJ2UOD37jF3Eox3NYYld7xgAkHB3jQU2bCOBXqEyQIgN9emWUninuv_h7ec_l3ECCBo3PbEavtziYvQ1VNLuSlvsC8OReaJkDixUcs6GaZDUKU9EM8lML0lUAK8mkqUQRpc3sFd2mTht-fiYL0YzIeKJ2LoeRFKiLnMFFJEW4GfuSV',
  FALSE,
  '[{"label": "距离", "value": "3.8 km"}, {"label": "接单速度", "value": "一般"}]'::jsonb
);

-- Insert dummy data for routes
INSERT INTO public.routes (type, duration_minutes, arrival_time, price, is_ai_recommended, segments)
VALUES 
(
  'fastest', 35, '14:15', 28.5, TRUE,
  '[{"type": "walk", "distance": "500m", "label": "步行"}, {"type": "subway", "name": "2号线", "label": "地铁"}, {"type": "car", "name": "快车", "label": "网约车"}]'::jsonb
),
(
  'cheapest', 55, '14:35', 4.0, FALSE,
  '[{"type": "walk", "distance": "100m", "label": "步行"}, {"type": "bus", "name": "112路", "label": "公交"}, {"type": "walk", "distance": "300m", "label": "步行"}]'::jsonb
);

-- Optionally, enable Row Level Security (RLS) if you want to expose anon read access
-- ALTER TABLE public.vehicles ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow anon read vehicles" ON public.vehicles FOR SELECT USING (true);
-- ALTER TABLE public.routes ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow anon read routes" ON public.routes FOR SELECT USING (true);
